### ISSUE TITLE
Não é possível especificar o tipo de dados das coleções em UIComponentField

### ISSUE THREAD

**Issue by lcbarcellos** [Rodolfocostapr/Experimento-Frameweb-Sec#1]
Quando o tipo de um atributo é definido como uma coleção (List ou Set), não é possível especificar o tipo de objeto presente na coleção. Assim o parâmetro fica definido como uma lista de Object.

Creio que este bug se aplique ao "upstream", ao projeto principal, mas como estou utilizando esta versão do editor, estou registrando aqui.

**Comment by Rodolfocostapr** [comment]
Bom dia, Luciano.
Tem como você registrar isso no issue tracker do repositório do frameweb
comum? Aí o Silas análisa e resolve.
https://github.com/nemo-ufes/FrameWeb
 Att,

Em qui, 20 de set de 2018 00:52, Luciano Coutinho Barcellos <
notifications@github.com> escreveu:

**Comment by lcbarcellos** [comment]
Registrando no projeto principal https://github.com/nemo-ufes/FrameWeb/issues/5
